plugins:
  - awesome-pages
  - include-markdown

site_name: FlagGems
theme:
  name: material
  language: en
  features:
    - content.code.copy

markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences

docs_dir: docs

nav:
  - Introduction: index.md
  - Get Start: get_start_with_flaggems.md
  - Pointwise Dynamic: pointwise_dynamic.md
  - Python Tests: pytest_in_flaggems.md
  - C++ Extension : build_flaggems_with_c_extensions.md
  - C++ Tests: ctest_in_flaggems.md
  - Operator List: operator_list.md
  - Performance: performance_and_benchmark.md
  - Countributing: code_countribution.md
  - Add A C++ wrapper: add_a_cpp_wrapper.md
