name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
labels: [Bug]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through the existing and past issues.
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If possible, provide a minimal code example to reproduce the error. Ensure the snippet is concise and includes all necessary imports, avoiding any external dependencies.

      Feel free to put the long code in a public gist and link.

      Please paste or describe the observed results, including the **full** error message and traceback if applicable. Wrap error messages in ```` ```triple quotes blocks``` ```` if possible.
    placeholder: |
      Description of the bug.

      Sample code to reproduce the problem.

      The error message with the full traceback.

  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thank you for your contributing 🎉!
