name: gems-test-on-hopper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: op-utils-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  op-test:
    runs-on: hopper
    concurrency:
      group: reduction-op-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FlagGems examples
        shell: bash
        run: |
          pytest -s tests/test_pointwise_dynamic.py
